<a href="https://colab.research.google.com/github/Rubinisuresh/Course_9/blob/main/Week_5_Dashboard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv("/content/m5_survey_data_technologies_normalised.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74590 entries, 0 to 74589
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              74589 non-null  float64
 1   LanguageWorkedWith      59792 non-null  object
 2   LanguageDesireNextYear  55764 non-null  object
 3   DatabaseWorkedWith      31375 non-null  object
 4   DatabaseDesireNextYear  29575 non-null  object
 5   PlatformWorkedWith      39208 non-null  object
 6   PlatformDesireNextYear  44314 non-null  object
 7   WebFrameWorkedWith      24803 non-null  object
 8   WebFrameDesireNextYear  24567 non-null  object
 9   DevEnviron              33306 non-null  object
 10  OpSys                   0 non-null      float64
 11  Containers              0 non-null      float64
 12  BlockchainOrg           0 non-null      float64
 13  BlockchainIs            0 non-null      float64
dtypes: float64(5), object(9)
memory usage: 8.0+ MB

In [5]:
df_lang = df.groupby('LanguageWorkedWith',axis=0).count()
df_lang.head(10)

,Respondent,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs
LanguageWorkedWith,,,,,,,,,,,,,
Assembly,437,432,417,384,432,430,373,355,437,0,0,0,0
Bash/Shell/PowerShell,4642,4598,4435,4143,4538,4462,4000,3837,4604,0,0,0,0
C,1578,1537,1318,1162,1461,1436,1029,955,1416,0,0,0,0
C#,4288,4103,3568,3219,3716,3743,3246,3106,3908,0,0,0,0
C++,1946,1850,1435,1247,1673,1663,1056,983,1619,0,0,0,0
Clojure,164,150,135,105,144,143,100,69,124,0,0,0,0
Dart,237,222,197,167,213,211,145,139,201,0,0,0,0
Elixir,187,180,154,130,166,157,133,100,138,0,0,0,0
Erlang,98,86,73,50,75,71,48,33,48,0,0,0,0
F#,158,146,96,75,107,116,71,41,114,0,0,0,0

In [21]:
df_lang.sort_values('Respondent',ascending=False,inplace=True)
df_lang['Respondent'].head(10)

LanguageWorkedWith
JavaScript               8687
HTML/CSS                 7830
SQL                      7106
Bash/Shell/PowerShell    4642
Python                   4542
Java                     4506
C#                       4288
TypeScript               3232
PHP                      2913
C++                      1946
Name: Respondent, dtype: int64

In [6]:
df_lang = df.groupby('DatabaseWorkedWith',axis=0).count()
df_lang.head(10)

,Respondent,LanguageWorkedWith,LanguageDesireNextYear,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs
DatabaseWorkedWith,,,,,,,,,,,,,
Cassandra,397,397,392,373,388,386,341,318,396,0,0,0,0
Couchbase,250,250,247,238,241,234,233,221,241,0,0,0,0
DynamoDB,831,829,814,777,824,804,760,692,820,0,0,0,0
Elasticsearch,1954,1936,1909,1801,1891,1843,1700,1574,1860,0,0,0,0
Firebase,1314,1309,1282,1210,1272,1240,1115,1061,1235,0,0,0,0
MariaDB,1709,1700,1655,1580,1620,1592,1485,1349,1569,0,0,0,0
Microsoft SQL Server,4110,4061,3913,3518,3717,3726,3306,3141,3790,0,0,0,0
MongoDB,3016,2953,2837,2560,2777,2709,2442,2212,2589,0,0,0,0
MySQL,5469,5313,4947,4117,4513,4562,3607,3357,4243,0,0,0,0
Oracle,1744,1659,1509,1164,1205,1317,875,862,1250,0,0,0,0

In [7]:
df_lang.sort_values('Respondent',ascending=False,inplace=True)
df_lang['Respondent'].head(10)

DatabaseWorkedWith
MySQL                   5469
Microsoft SQL Server    4110
PostgreSQL              4097
SQLite                  3248
MongoDB                 3016
Redis                   2508
Elasticsearch           1954
Oracle                  1744
MariaDB                 1709
Firebase                1314
Name: Respondent, dtype: int64

In [8]:
df_lang = df.groupby('WebFrameWorkedWith',axis=0).count()
df_lang.head(10)

,Respondent,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs
WebFrameWorkedWith,,,,,,,,,,,,,
ASP.NET,3042,3026,2965,2737,2570,2727,2796,2754,2975,0,0,0,0
Angular/Angular.js,3327,3324,3282,3244,3086,3192,3152,3151,3317,0,0,0,0
Django,1176,1174,1147,1129,1040,1128,1101,1047,1120,0,0,0,0
Drupal,291,289,279,273,245,271,257,242,264,0,0,0,0
Express,2028,2019,1936,1833,1665,1855,1829,1773,1738,0,0,0,0
Flask,1186,1168,1118,1063,921,1103,1074,909,1008,0,0,0,0
Laravel,939,920,853,755,699,758,759,703,670,0,0,0,0
Other(s):,814,774,720,566,495,592,617,458,528,0,0,0,0
React.js,3302,3159,2910,2218,1954,2542,2528,2010,2072,0,0,0,0
Ruby on Rails,856,826,760,635,528,678,667,490,475,0,0,0,0

In [9]:
df_lang.sort_values('Respondent',ascending=False,inplace=True)
df_lang['Respondent'].head(10)

WebFrameWorkedWith
jQuery                4629
Angular/Angular.js    3327
React.js              3302
ASP.NET               3042
Express               2028
Spring                1728
Vue.js                1485
Flask                 1186
Django                1176
Laravel                939
Name: Respondent, dtype: int64

In [5]:
df_lang = df.groupby('LanguageDesireNextYear',axis=0).count()
df_lang.head(10)

,Respondent,LanguageWorkedWith,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs
LanguageDesireNextYear,,,,,,,,,,,,,
Assembly,336,335,320,293,329,329,273,262,336,0,0,0,0
Bash/Shell/PowerShell,3097,3096,2943,2868,3002,3015,2653,2622,3066,0,0,0,0
C,1028,1025,847,803,951,961,667,667,935,0,0,0,0
C#,3591,3557,3045,2949,3117,3316,2804,2852,3376,0,0,0,0
C++,1633,1619,1214,1171,1405,1470,955,967,1413,0,0,0,0
Clojure,413,408,355,339,368,373,308,279,362,0,0,0,0
Dart,610,606,519,511,539,578,439,458,543,0,0,0,0
Elixir,620,609,509,509,541,586,475,468,516,0,0,0,0
Erlang,310,292,223,212,241,253,169,167,210,0,0,0,0
F#,621,586,367,365,416,505,348,318,466,0,0,0,0

In [6]:
df_lang.sort_values('Respondent',ascending=False,inplace=True)
df_lang['Respondent'].head(10)

LanguageDesireNextYear
JavaScript               6630
HTML/CSS                 5328
Python                   5239
SQL                      5012
TypeScript               4088
C#                       3591
Bash/Shell/PowerShell    3097
Java                     2953
Go                       2759
Kotlin                   1890
Name: Respondent, dtype: int64

In [4]:
df_lang = df.groupby('DatabaseDesireNextYear',axis=0).count()
df_lang.head(10)

,Respondent,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs
DatabaseDesireNextYear,,,,,,,,,,,,,
Cassandra,1003,1001,989,987,983,975,889,874,1002,0,0,0,0
Couchbase,390,388,382,370,370,376,331,340,367,0,0,0,0
DynamoDB,1044,1031,1026,1000,983,1010,899,896,1004,0,0,0,0
Elasticsearch,2856,2813,2789,2694,2637,2733,2397,2374,2668,0,0,0,0
Firebase,1650,1612,1604,1482,1469,1565,1328,1367,1482,0,0,0,0
MariaDB,1385,1350,1352,1270,1231,1313,1062,1090,1192,0,0,0,0
Microsoft SQL Server,2706,2626,2643,2301,2194,2484,1955,2098,2380,0,0,0,0
MongoDB,3649,3510,3481,3073,3046,3343,2625,2830,3040,0,0,0,0
MySQL,3281,3068,3093,2524,2402,2816,1858,2070,2394,0,0,0,0
Oracle,870,766,804,559,490,693,351,468,573,0,0,0,0

In [5]:
df_lang.sort_values('Respondent',ascending=False,inplace=True)
df_lang['Respondent'].head(10)

DatabaseDesireNextYear
PostgreSQL              4328
MongoDB                 3649
Redis                   3331
MySQL                   3281
Elasticsearch           2856
Microsoft SQL Server    2706
SQLite                  2437
Firebase                1650
MariaDB                 1385
DynamoDB                1044
Name: Respondent, dtype: int64

In [6]:
df_lang = df.groupby('WebFrameDesireNextYear',axis=0).count()
df_lang.head(10)

,Respondent,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs
WebFrameDesireNextYear,,,,,,,,,,,,,
ASP.NET,2382,2360,2350,2048,2055,2063,2234,2194,2325,0,0,0,0
Angular/Angular.js,3059,3055,3024,2973,2886,2928,2942,2919,3049,0,0,0,0
Django,1504,1496,1475,1358,1378,1379,1428,1303,1441,0,0,0,0
Drupal,168,166,167,143,151,135,160,135,150,0,0,0,0
Express,1957,1937,1927,1687,1738,1737,1826,1780,1732,0,0,0,0
Flask,1240,1205,1196,1027,1058,1094,1165,964,1089,0,0,0,0
Laravel,863,825,811,652,704,662,747,614,637,0,0,0,0
Other(s):,762,715,717,553,528,576,618,581,534,0,0,0,0
React.js,4714,4476,4465,3169,3284,3450,3994,3339,3410,0,0,0,0
Ruby on Rails,970,879,923,611,645,665,792,599,585,0,0,0,0

In [7]:
df_lang.sort_values('Respondent',ascending=False,inplace=True)
df_lang['Respondent'].head(10)

WebFrameDesireNextYear
React.js              4714
Vue.js                3143
Angular/Angular.js    3059
ASP.NET               2382
jQuery                2241
Express               1957
Spring                1564
Django                1504
Flask                 1240
Ruby on Rails          970
Name: Respondent, dtype: int64

In [8]:
df = pd.read_csv("/content/m5_survey_data_demographics.csv")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11398 entries, 0 to 11397
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Respondent      11398 non-null  int64
 1   MainBranch      11398 non-null  object
 2   Hobbyist        11398 non-null  object
 3   OpenSourcer     11398 non-null  object
 4   OpenSource      11317 non-null  object
 5   Employment      11398 non-null  object
 6   Country         11398 non-null  object
 7   Student         11347 non-null  object
 8   EdLevel         11286 non-null  object
 9   UndergradMajor  10661 non-null  object
 10  EduOther        11234 non-null  object
 11  OrgSize         11302 non-null  object
 12  DevType         11333 non-null  object
 13  YearsCode       11389 non-null  object
 14  Age1stCode      11385 non-null  object
 15  YearsCodePro    11382 non-null  object
 16  CareerSat       11398 non-null  object
 17  JobSat          11397 non-null  object
 18  MgrIdiot        10905 non-null  object
 19  MgrMoney        10901 non-null  object
 20  MgrWant         10905 non-null  object
 21  JobSeek         11398 non-null  object
 22  LastHireDate    11398 non-null  object
 23  LastInt         10985 non-null  object
 24  FizzBuzz        11361 non-null  object
 25  JobFactors      11395 non-null  object
 26  ResumeUpdate    11359 non-null  object
 27  CurrencySymbol  11398 non-null  object
 28  CurrencyDesc    11398 non-null  object
 29  CompTotal       10589 non-null  float64
 30  CompFreq        11192 non-null  object
 31  ConvertedComp   10582 non-null  float64
 32  WorkWeekHrs     11276 non-null  float64
 33  WorkPlan        11277 non-null  object
 34  WorkChallenge   11234 non-null  object
 35  WorkRemote      11390 non-null  object
 36  WorkLoc         11366 non-null  object
 37  ImpSyn          11393 non-null  object
 38  CodeRev         11397 non-null  object
 39  CodeRevHrs      8972 non-null   float64
 40  UnitTests       11369 non-null  object
 41  PurchaseHow     11202 non-null  object
 42  PurchaseWhat    11360 non-null  object
 43  BetterLife      11300 non-null  object
 44  ITperson        11363 non-null  object
 45  OffOn           11360 non-null  object
 46  SocialMedia     11105 non-null  object
 47  Extraversion    11378 non-null  object
 48  ScreenName      10891 non-null  object
 49  SOVisit1st      11073 non-null  object
 50  SOVisitFreq     11393 non-null  object
 51  SOVisitTo       11397 non-null  object
 52  SOFindAnswer    11395 non-null  object
 53  SOTimeSaved     11348 non-null  object
 54  SOHowMuchTime   9481 non-null   object
 55  SOAccount       11397 non-null  object
 56  SOPartFreq      10270 non-null  object
 57  SOJobs          11392 non-null  object
 58  EntTeams        11393 non-null  object
 59  SOComm          11398 non-null  object
 60  WelcomeChange   11313 non-null  object
 61  SONewContent    9433 non-null   object
 62  Age             11111 non-null  float64
 63  Gender          11325 non-null  object
 64  Trans           11275 non-null  object
 65  Sexuality       10856 non-null  object
 66  Ethnicity       10723 non-null  object
 67  Dependents      11258 non-null  object
 68  SurveyLength    11379 non-null  object
 69  SurveyEase      11384 non-null  object
dtypes: float64(5), int64(1), object(64)
memory usage: 6.1+ MB

In [ ]:
df_lang = df.groupby('WebFrameDesireNextYear',axis=0).count()
df_lang.head(10)

In [2]:
df = pd.read_csv("/content/marketing_sample_for_naukri_com-jobs__20190701_20190830__30k_data.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Uniq Id                  30000 non-null  object
 1   Crawl Timestamp          30000 non-null  object
 2   Job Title                29425 non-null  object
 3   Job Salary               29950 non-null  object
 4   Job Experience Required  29427 non-null  object
 5   Key Skills               28729 non-null  object
 6   Role Category            27695 non-null  object
 7   Location                 29423 non-null  object
 8   Functional Area          29427 non-null  object
 9   Industry                 29427 non-null  object
 10  Role                     29099 non-null  object
dtypes: object(11)
memory usage: 2.5+ MB

In [6]:
df.describe()

,Uniq Id,Crawl Timestamp,Job Title,Job Salary,Job Experience Required,Key Skills,Role Category,Location,Functional Area,Industry,Role
count,30000,30000,29425,29950,29427,28729,27695,29423,29427,29427,29099
unique,30000,28865,23884,1258,256,26909,206,2573,72,122,649
top,9be62c49a0b7ebe982a4af1edaa7bc5f,2019-08-04 02:01:21 +0000,Sales Executive,Not Disclosed by Recruiter,2 - 5 yrs,Counselor| Mentor| Trainer| Advisor| Teaching,Programming & Design,Bengaluru,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Software Developer
freq,1,5,120,19731,2002,102,8551,4986,7400,10012,6396

In [14]:
df['Role Category']

0                                       Advertising
1                                      Retail Sales
2                                               R&D
3        Admin/Maintenance/Security/Datawarehousing
4                              Programming & Design
                            ...
29995                          Programming & Design
29996                                    Operations
29997                              University Level
29998                          Programming & Design
29999                      Online/Digital Marketing
Name: Role Category, Length: 30000, dtype: object

In [8]:
df['Job Title'].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
29995    False
29996    False
29997    False
29998    False
29999    False
Name: Job Title, Length: 30000, dtype: bool

In [9]:
df['Job Title'].dropna()

0                                    Digital Media Planner
1                                 Online Bidding Executive
2         Trainee Research/ Research Executive- Hi- Tec...
3                                        Technical Support
4                        Software Test Engineer -hyderabad
                               ...
29995                                MTS-Software-Engineer
29996                          Client Relationship Manager
29997                                     Assoc. Prof.- CS
29998           Application/Cyber Security Specialist-Pune
29999                           Press Release Writer - SEO
Name: Job Title, Length: 29425, dtype: object

In [10]:
df['Job Title'].isnull().sum()

575